roles:
  - Actors
  - Graphic Designers
  - Musicians and Singers
  - Registered Nurses
  - Pharmacists
  - Psychiatrists
  - Software Developers
  - Information Security Analysts
  - Data Scientists
  - Chemists
  - Chief Executives
  - Human Resources Managers
  - Financial and Investment Analysts
  - Detectives and Criminal Investigators
  - Firefighters
  - Air Traffic Controllers
  - Machinists
  - Farmers, Ranchers, and Other Agricultural Managers
  - Elementary School Teachers, Except Special Education
  - Judges, Magistrate Judges, and Magistrates