realistic:
  description: "Likes to work with animals, tools, or machines; generally avoids social activities like teaching, healing, and informing others; Has good skills in working with tools, mechanical or electrical drawings, machines, or plants and animals; Values practical things you can see, touch, and use like plants and animals, tools, equipment, or machines; and Sees self as practical, mechanical, and realistic."
  characteristics:
    - "I like to work on cars."
    - "I like to build things."
    - "I like to take care of animals."
    - "I like putting things together or assembling things."
    - "I like to cook."
    - "I am a practical person."
    - "I like working outdoors."
investigative:
  description: "Likes to study and solve math or science problems; generally avoids leading, selling, or persuading people; Is good at understanding and solving science and math problems; Values science; and Sees self as precise, scientific, and intellectual."
  characteristics:
    - "I like to do puzzles."
    - "I like to do experiments."
    - "I enjoy science."
    - "I like to analyze things (problems/situations)."
    - "I like working with numbers or charts."
    - "I'm good at math."
artistic:
  description: "Likes to do creative activities like art, drama, crafts, dance, music, or creative writing; generally avoids highly ordered or repetitive activities; Has good artistic abilities -- in creative writing, drama, crafts, music, or art; Values the creative arts -- like drama, music, art, or the works of creative writers; and Sees self as expressive, original, and independent."
  characteristics:
    - "I am good at working independently."
    - "I like to read about art or music."
    - "I enjoy creative"
    - "I am a creative person."
    - "I like to play instruments or sing."
    - "I like acting in plays."
    - "I like to draw."
social:
  description: "Likes to do things to help people -- like, teaching, nursing, or giving first aid, providing information; generally avoids using machines, tools, or animals to achieve a goal; Is good at teaching, counseling, nursing, or giving information; Values helping people and solving social problems; and Sees self as helpful, friendly, and trustworthy."
  characteristics:
    - "I like to work in teams."
    - "I like to train or teach people."
    - "I like trying to help people solve their problems."
    - "I am interested in helping people."
    - "I enjoy learning about other cultures."
    - "I like to get into discussions about issues."
    - "I like helping people."
enterprising:
  description: "Likes to lead and persuade people, and to sell things and ideas; generally avoids activities that require careful observation and scientific, analytical thinking; Is good at leading people and selling things or ideas; Values success in politics, leadership, or business; and Sees self as energetic, ambitious, and sociable."
  characteristics:
    - "I am ambitious person, I set goals for myself."
    - "I like to try to influence or persuade people."
    - "I like selling things."
    - "I am quick to take on new responsibilities."
    - "I would like to start my own business."
    - "I like to lead."
    - "I like to give speeches."
conventional:
  description: "Likes to work with numbers, records, or machines in a set, orderly way; generally avoids ambiguous, unstructured activities Is good at working with written records and numbers in a systematic, orderly way; Values success in business; and Sees self as orderly, and good at following a set plan."
  characteristics:
    - "I like to organize things, (files, desks/offices)."
    - "I ike to have clear instructions to follow."
    - "I wouldn't mind working 8 hours per day in an office."
    - "I pay attention to details."
    - "I like to do filing or typing."
    - "I am good at keeping records of my work."
    - "I would like to work in an office."
